# Generated by Django 3.1.5 on 2021-01-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20210121_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('not_read', 'Не прочитано'), ('read', 'Прочтено'), ('in_progress', 'Читаю')], default='not_read', max_length=15, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
